config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students#, only: [:create, :destroy]
#Aug_25  
resources :users

resources :users do #12.15
    member do
     get :following, :followers
    end
 end

resources :users do
    resources :students
  end

resources :articles do
    resources :students
end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/


#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
#  devise_for :users
#  devise_for :admin_users, ActiveAdmin::Devise.config
  
#ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/models/student.rb
#Листинг 6.24: Валидация уникальности адресов электронной почты. ЗЕЛЕНЫЙ app/models/user.rb  !!!
class Student < ActiveRecord::Base
default_scope -> { order(id: :asc) }
belongs_to :user
validates :user_id, presence: true, uniqueness: true

validates:fio, presence: true 
#validates :country, presence: true          
#validates :lastname, presence: true
#validates :firstname, presence: true
end


   private
     def student_params
           params.require(:student).permit(:fio, :user_id)
     end

app/controllers/students_controller.rb
#from ch12_march24
class StudentsController < InheritedResources::Base

  private

    def student_params
      params.require(:student).permit(:country, :fio, :lastname, :firstname, :email, :comment, :user_id)
    end
end

app/views/students/'_form.html.erb
March_21
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
    <%= f.label :studid %><br>
    <%= f.number_field :id %>
  </div>

<div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :id %>
  </div>

 <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id  %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>


  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  
  

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_form.erb
March_23 /students/_form
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

user_id
 <div class="field">
    <%= f.label :userxid %><br>
    <%= f.number_field :user_id  %>
  </div>

<div class="field">
    <%= f.label :studentsid %><br>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  
 <!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_micropost_form.html.erb  11.57 :11.62  shared/_micropost_form.html.erb -->
<br>
#fio
   <div class="field">
    <%#= f.text_area :user_id, placeholder: "Compose new student..." %>
<%#= f.text_field :fio, placeholder: "Compose new student..." %>
  </div>
 <br> 
  <%= f.submit "Save up as student", class: "btn btn-primary" %>

 <span class="picture">
        <%#= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
               <%# end %>
               <div class="actions">
                   <%#= f.submit %>
                 </div>
<% end %>

app/views/students/_form_with model.html.erb
#March_21 2021 http://rusrails.ru/rails-form-helpers


<%= form_with model: @user do |form| %>
  Students:
  <ul>
    <%= form.fields_for :students do |students_form| %>
      <li>
        <%= students_form.label :fio %>
        <%= students_form.text_field :fio %>

        <%= students_form.label :user_id %>
        <%= students_form.text_field :user_id %>
        ...
      </li>
    <% end %>
  </ul>
<% end %>

app/views/students/_student.html.erb
 #Листинг 11.21: Партиал для отображения единичного микросообщения. app/views/microposts/_micropost.html.erb  11.49 :11.59 
<li id="<%= student.id %>">
  <%#= link_to gravatar_for(micropost.user) %>
 <span class="user"><%= link_to student.user.name, student.user %></span>
  
<span class="id"><%= student.user_id %></span>
 <%#= image_tag micropost.picture.url if micropost.picture? %>
<span class="timestamp">
</span>
  <!-- :11.49 удаление micropost -->
Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/students/_studfio.html.erb
 #Листинг 11.21: Партиал для отображения единичного микросообщения. app/views/microposts/_micropost.html.erb  11.49 :11.59 
<li id="<%= student.id %>">
  <%#= link_to gravatar_for(micropost.user) %>
 <span class="user"><%= link_to student.user.name, student.user %></span>
  
<span class="id">
<%= student.id %></span>
 </span>

<%#= image_tag micropost.picture.url if micropost.picture? %>
<span class="timestamp">
</span>
  <!-- :11.49 удаление micropost -->
Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

===================================================
-->
<li id="<%= student.id %>">
<% end %>
<span class="user"><%= link_to student.user.name, student.user %></span>

app/views/students/edit.html.erb
<!--#Листинг 9.2: Представление для редактирования пользователя app/views/users/#edit.html.erb  :11.42 #Листинг 11.42: :edit-->
<% provide(:title, "Edit user") %>
<h1>Update user and student</h1>

<!--#March_21 2021 http://rusrails.ru/rails-form-helpers -->
<% @user ||= current_user %>
<%= form_with model: @user do |form| %>
<%= render 'shared/error_messages', object: form.object %>
   
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>

      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control' %>
     
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>

      <%= form.label :password_confirmation, "Confirmation" %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>

    
  <p>Students:
  
    <%= form.fields_for :students do |students_form| %>
      <li>
          <%= students_form.label :userid %>
          <%= students_form.text_field :user_id %>

          <%= students_form.label :country %>
          <%= students_form.text_field :country %>

        <%= students_form.label :fio %>
        <%= students_form.text_field :fio %>


<%= students_form.label :lastname %>
        <%= students_form.text_field :lastname %>

<%= students_form.label :firstname %>
        <%= students_form.text_field :firstname %>

<%= students_form.label :comment %>
        <%= students_form.text_field :comment %>

       
        <%#= students_form.submit "Save student changes", class: "btn btn-primary" %>
<%= form.submit "Save form user+students changes", class: "btn btn-primary" %>
      </li>

<% end %>
 
<% end %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Country</th>
      <th>Fio</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Email</th>
      <th>Comment</th>
      <th>User_id</th>
<th>Student_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>table-hover
    <% @students.each do |student| %>
      <tr>
        <td><%= student.country %></td>
        <td><%= student.fio %></td>
        <td><%= student.lastname %></td>
        <td><%= student.firstname %></td>
        <td><%= student.email %></td>
        <td><%= student.comment %></td>
        <td><%= student.user_id %></td>
<td><%= student.id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student Sept_20</h1>


<section class="student">
                 this creates<%= render 'shared/student_form' %>
           </section>
<%# end %>

#<%#= render 'form' %>

<%#= link_to 'Back', students_path %>

<h1>New student</h1>
 students/new.html.erb
<%#= render 'form' %>

<%= link_to 'Back', students_path %>

--- !ruby/hash:ActionController::Parameters
utf8: "✓"
authenticity_token: Gtgw7NppMABxZlN+ms+IqoyJU5cYZS2FPqncUaTRI9M=
student: !ruby/hash:ActionController::Parameters
  user_id: '2'
  fio: fio2
  country: two
commit: Post
action: create
controller: students
===================
March_23 Aug_26  2021 /students/_form
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


user_id
 <div class="field">
    <%= f.label :userid! %><br>
    <%= f.number_field :user_id  %>
  </div>

<div class="field">
    <%= f.label :studentid %><br>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  
 <!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_micropost_form.html.erb  11.57 :11.62  shared/_micropost_form.html.erb -->

   
  
  <%= f.submit "Sign up as student", class: "btn btn-primary" %>

 <span class="picture">
        <%#= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
              
               <div class="actions">
                   <%#= f.submit %>
                 </div>
<% end %>

app/views/students/show.html.erb
<h1>New student Sept_20</h1>

<!-- #libr  Sept 01 Листинг 7.10: Добавление боковой панели к представлению пользователя show. app/views/users/show.html.erb
#Листинг 7.4:Листинг 7.8:Листинг 7.10 :11.23 :12.23-->
<p><p><p>
<%# provide(:title, @user.name) %> 
<%#no! provide(:title, @current_user.name) %> 
<% @user ||= current_user %>
<%#Sept_20 !!  =@current_user.name %>

<!--<li><%#= link_to "Create student", root_path %></li> -->
 


<div class="row">
  <aside class="col-md-4">
         <section>
           <h1>
      @current_user.name=<%= @current_user.name %>
@current_user.id=<%= @current_user.id%>
           </h1>
         </section>
<section class="stats">
      <%#= render 'shared/stats' %>
    </section>

  </aside>

  <div class="col-md-8">
    <%#= render 'follow_form' if logged_in? %>
    <%# if @user.microposts.any? %>
  <!--    <h3>(<%#= @user.microposts.count %>) Microposts of the user = <%= @user.name %>  </h3>  --> 
      <ol class="microposts">
        <%#= render @microposts %>
      </ol>
      <%#= will_paginate @microposts %>
    <%# end %>
<%# end %>
  </div>
</div>
<section class="student">
                 <%= render 'shared/student_form' %>
           </section>